version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nodejs-api:
    image: node:18.13.0
    container_name: ${API_CONTAINER_NAME}
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      PG_HOST: ${PG_HOST}
      PG_PORT: 5432
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
    depends_on:
      - postgres
    command: sh -c "npm install rimraf -g && rimraf node_modules && npm install && node ace migration:run && node ace test && node ace serve"

volumes:
  postgres-data:
